USE DATABASE AIRLINE_DWH;

UPDATE INTEGRATION.FACT_FLIGHTS SET FLIGHT_STATUS = 'Unknown' WHERE FLIGHT_ID = 1;

SELECT * FROM INTEGRATION.FACT_FLIGHTS WHERE FLIGHT_ID = 1;

-- DML 1
SELECT * FROM INTEGRATION.FACT_FLIGHTS AT(OFFSET => -60*2) WHERE FLIGHT_ID = 1;

-- DML 2
CREATE TABLE INTEGRATION.FACT_FLIGHTS_BACKUP AS
SELECT * FROM INTEGRATION.FACT_FLIGHTS AT(OFFSET => -60*2);

-- DDL 1
DROP TABLE MART.RPT_FLIGHT_STATS;

-- DDL 2
UNDROP TABLE MART.RPT_FLIGHT_STATS;

SELECT * FROM MART.RPT_FLIGHT_STATS;
