USE DATABASE AIRLINE_DWH;

CREATE OR REPLACE TABLE UTILS.ACCESS_CONTROL (
    USER_NAME VARCHAR,
    ALLOWED_TICKET_TYPE VARCHAR
);

INSERT INTO UTILS.ACCESS_CONTROL (USER_NAME, ALLOWED_TICKET_TYPE)
VALUES (CURRENT_USER(), 'Business');

CREATE OR REPLACE ROW ACCESS POLICY UTILS.TICKET_POLICY
AS (TICKET_VAL VARCHAR) RETURNS BOOLEAN ->
    EXISTS (
        SELECT 1 FROM UTILS.ACCESS_CONTROL
        WHERE USER_NAME = CURRENT_USER()
        AND ALLOWED_TICKET_TYPE = TICKET_VAL
    );

CREATE OR REPLACE SECURE VIEW MART.SECURE_FLIGHT_REPORT AS
SELECT * FROM INTEGRATION.FACT_FLIGHTS;

ALTER VIEW MART.SECURE_FLIGHT_REPORT
ADD ROW ACCESS POLICY UTILS.TICKET_POLICY ON (TICKET_TYPE);
