CREATE DATABASE IF NOT EXISTS AIRLINE_DWH;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WITH WAREHOUSE_SIZE='X-SMALL';
USE DATABASE AIRLINE_DWH;

-- Create Schema Layers
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS INTEGRATION;
CREATE SCHEMA IF NOT EXISTS MART;
CREATE SCHEMA IF NOT EXISTS UTILS;

-- Standard CSV Format
CREATE OR REPLACE FILE FORMAT UTILS.CSV_FORMAT
    TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n'
        SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('NULL', 'null', '');

-- Internal Stage
CREATE OR REPLACE STAGE UTILS.RAW_DATA_STAGE FILE_FORMAT = UTILS.CSV_FORMAT;