USE DATABASE AIRLINE_DWH;

-- Raw Landing Table
CREATE OR REPLACE TABLE RAW.RAW_FLIGHTS (
    INDEX INT, PASSENGER_ID VARCHAR(50), FIRST_NAME VARCHAR(100), LAST_NAME VARCHAR(100),
    GENDER VARCHAR(20), AGE INT, NATIONALITY VARCHAR(100), AIRPORT_NAME VARCHAR(200),
    AIRPORT_COUNTRY_CODE VARCHAR(10), COUNTRY_NAME VARCHAR(100), AIRPORT_CONTINENT VARCHAR(50),
    CONTINENTS VARCHAR(50), DEPARTURE_DATE DATE, ARRIVAL_AIRPORT VARCHAR(10), PILOT_NAME VARCHAR(100),
    FLIGHT_STATUS VARCHAR(50), TICKET_TYPE VARCHAR(50), PASSENGER_STATUS VARCHAR(50),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
ALTER TABLE RAW.RAW_FLIGHTS SET CHANGE_TRACKING = TRUE;

-- CDC Stream to capture new inserts
CREATE OR REPLACE STREAM RAW.STR_RAW_FLIGHTS ON TABLE RAW.RAW_FLIGHTS;

-- Integration Dimensions & Facts
CREATE OR REPLACE TABLE INTEGRATION.DIM_PASSENGER (
    PASSENGER_KEY VARCHAR(50) PRIMARY KEY, FIRST_NAME VARCHAR(100), LAST_NAME VARCHAR(100),
    GENDER VARCHAR(20), AGE INT, NATIONALITY VARCHAR(100)
);

CREATE OR REPLACE TABLE INTEGRATION.DIM_AIRPORT (
    AIRPORT_CODE VARCHAR(10) PRIMARY KEY, AIRPORT_NAME VARCHAR(200), COUNTRY_CODE VARCHAR(10),
    COUNTRY_NAME VARCHAR(100), CONTINENT VARCHAR(50)
);

CREATE OR REPLACE TABLE INTEGRATION.FACT_FLIGHTS (
    FLIGHT_ID NUMBER AUTOINCREMENT, PASSENGER_KEY VARCHAR(50), ARRIVAL_AIRPORT_KEY VARCHAR(10),
    DEPARTURE_DATE DATE, PILOT_NAME VARCHAR(100), FLIGHT_STATUS VARCHAR(50),
    TICKET_TYPE VARCHAR(50), PASSENGER_STATUS VARCHAR(50),
    FOREIGN KEY (PASSENGER_KEY) REFERENCES INTEGRATION.DIM_PASSENGER(PASSENGER_KEY),
    FOREIGN KEY (ARRIVAL_AIRPORT_KEY) REFERENCES INTEGRATION.DIM_AIRPORT(AIRPORT_CODE)
);

-- Reporting Mart
CREATE OR REPLACE TABLE MART.RPT_FLIGHT_STATS (
    REPORT_DATE DATE, CONTINENT VARCHAR(50), TOTAL_FLIGHTS INT,
    DELAYED_FLIGHTS INT, LAST_UPDATED TIMESTAMP_NTZ
);

-- Audit Logging
CREATE OR REPLACE TABLE UTILS.ETL_LOGS (
    LOG_ID NUMBER AUTOINCREMENT, PROCESS_NAME VARCHAR(100), STATUS VARCHAR(20),
    ROWS_AFFECTED INT, LOG_MESSAGE VARCHAR(500), LOG_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);