CREATE OR REPLACE PROCEDURE AIRLINE_DWH.RAW.SP_INGEST_FLIGHTS_FROM_STAGE(FILE_NAME VARCHAR)
RETURNS STRING LANGUAGE SQL AS
$$
BEGIN
    -- Load data from Internal Stage to Raw Table
EXECUTE IMMEDIATE 'COPY INTO AIRLINE_DWH.RAW.RAW_FLIGHTS
                       (INDEX, PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY,
                        AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT,
                        CONTINENTS, DEPARTURE_DATE, ARRIVAL_AIRPORT, PILOT_NAME, FLIGHT_STATUS,
                        TICKET_TYPE, PASSENGER_STATUS)
                       FROM @AIRLINE_DWH.UTILS.RAW_DATA_STAGE/' || :FILE_NAME || '
                       FILE_FORMAT = (FORMAT_NAME = AIRLINE_DWH.UTILS.CSV_FORMAT)
                       ON_ERROR = CONTINUE';

INSERT INTO AIRLINE_DWH.UTILS.ETL_LOGS (PROCESS_NAME, STATUS, ROWS_AFFECTED, LOG_MESSAGE)
VALUES ('SP_INGEST_FLIGHTS_FROM_STAGE', 'SUCCESS', (SELECT COUNT(*) FROM AIRLINE_DWH.RAW.RAW_FLIGHTS WHERE LOAD_TIMESTAMP >= DATEADD(minute, -1, CURRENT_TIMESTAMP())), 'Loaded file ' || :FILE_NAME);

RETURN 'Success';
END;
$$;