CREATE OR REPLACE PROCEDURE AIRLINE_DWH.MART.SP_BUILD_REPORT_FLIGHT_STATS()
RETURNS STRING LANGUAGE SQL AS
$$
DECLARE
row_count INT DEFAULT 0;
BEGIN
TRUNCATE TABLE AIRLINE_DWH.MART.RPT_FLIGHT_STATS;

INSERT INTO AIRLINE_DWH.MART.RPT_FLIGHT_STATS (REPORT_DATE, CONTINENT, TOTAL_FLIGHTS, DELAYED_FLIGHTS, LAST_UPDATED)
SELECT F.DEPARTURE_DATE, A.CONTINENT, COUNT(F.FLIGHT_ID), COUNT(CASE WHEN F.FLIGHT_STATUS = 'Delayed' THEN 1 END), CURRENT_TIMESTAMP()
FROM AIRLINE_DWH.INTEGRATION.FACT_FLIGHTS F
         JOIN AIRLINE_DWH.INTEGRATION.DIM_AIRPORT A ON F.ARRIVAL_AIRPORT_KEY = A.AIRPORT_CODE
GROUP BY 1, 2;

row_count := SQLROWCOUNT;

INSERT INTO AIRLINE_DWH.UTILS.ETL_LOGS (PROCESS_NAME, STATUS, ROWS_AFFECTED, LOG_MESSAGE)
VALUES ('SP_BUILD_REPORT_FLIGHT_STATS', 'SUCCESS', :row_count, 'Aggregated Data Refreshed');

RETURN 'Success';
END;
$$;